version: '3.7'

services:
    web_app:
        build:
            dockerfile: Dockerfile
            context: .
        image: web_fastapi
        container_name: fastapinew
        command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8000
        ports: 
            - "8000:8000"
        environment:
            - DATABASE_URL=mongodb://username:password@localhost:27017/database?authSource=admin
        # env_file:
        #     - .env

networks:
    default:
        external:
            name: to-do-network
