version: '3.7'

services:
  flask:
    container_name: flasknote
    build:
      context: .
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    volumes:
      - .:/usr/flasknote
    ports:
      - 5000:5000
    command: sh -c "flask run --host=0.0.0.0 --port=5000"

networks:
  default:
    name: web_dev
