version: '3.7'

services:
  flask:
    container_name: flasknote
    build:
      context: .
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      # - DB=mongodb://mongodb:27017
    volumes:
      - .:/usr/flasknote
    ports:
      - 5000:5000
    command: sh -c "flask run --host=0.0.0.0 --port=5000"
    links:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - AUTH=no
    volumes:
      # - .:/usr/flasknote/data
      - ./usr/flasknote/data:/usr/flasknote/data
      # - mongo-config:/data/configdb
    ports:
      - 27017:27017
    # command: mongod --logpath=/dev/null # --quiet

volumes:
  data:

networks:
  default:
    name: web_dev