texto = 'Linguagem Python'

print(len(texto))
print(texto.isupper())
print(texto.upper())
print(type(texto))
print(texto[2])
print(texto[2:8])
print(texto[:2])
print(texto[2:])
print(texto[2::2])
print(texto[-2])
print(texto[-8:-2])
print(texto[:-2])
print(texto[:-2])
print(texto[:-2:2])
